### ISSUE TITLE
ASM

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/DefaultSkin#1]
Darkhax has suggested to change the texture directly using access transformers instead of ASM.

He has suggested to use similar code to [here](https://github.com/Darkhax-Minecraft/Bookshelf/search?utf8=%E2%9C%93&q=setplayertexture).

**Comment by elifoster** [comment]
@xbony2 Do you think it would be overkill to simply depend on Bookshelf? Seems like a much more logical thing to do than reinvent the wheel here.

**Comment by xbony2** [comment]
You could just use some of their code.
